steps:
    - label: ":shipit: Deploy the Thing :tm: "
      command: ./scripts/deploy.sh
      agents:
        queue: vault
      plugins:
        - vault-secrets#v2.2.0:
            server: "http://localhost:8200"
            path: secret/buildkite
            auth:
              method: "approle"
              role-id: "${VAULT_ROLE_ID}"
  
    - wait

    - label: ":disguised_face: Deploy the thing (with OIDC) :tm:"
      skip: true
      command: ./scripts/deploy.sh
      agents:
        queue: vault
      plugins:
        - vault-secrets#v2.2.0:
            server: "http://localhost:8200"
            path: secret/buildkite
            auth:
              method: jwt
              jwt-role: buildkite
              jwt-env: "VAULT_JWT"

    - wait
    
    - label: ":shipit: Get secret from mountpath kv/ :tm: "
      command: ./scripts/secret.sh
      agents:
        queue: vault
      plugins:
      - file:///Users/jeremy/dev/plugins/vault-secrets-buildkite-plugin#sup-5798-json-secret-output:
            server: "http://localhost:8200"
            path: secret/buildkite/vault-buildkite-demo
            output: json
            auth:
              method: "approle"
              role-id: "${VAULT_ROLE_ID}"
              
    - label: ":vault: :bomb: clean up"
      command: docker compose down
      agents:
        queue: vault

